/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi;

import java.awt.AWTError.*;
import java.awt.AWTEvent.*;
import javax.swing.*;
/**
 *
 * @author Admin
 */
public class Aplikasi extends javax.swing.JFrame {
    
    int a,b,c;
    String hasil;
   
    
    public Aplikasi() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngdm = new javax.swing.ButtonGroup();
        topuplabel = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lbldm = new javax.swing.JLabel();
        rd15 = new javax.swing.JRadioButton();
        rd50 = new javax.swing.JRadioButton();
        rd125 = new javax.swing.JRadioButton();
        rd275 = new javax.swing.JRadioButton();
        rd550 = new javax.swing.JRadioButton();
        rd725 = new javax.swing.JRadioButton();
        rd1000 = new javax.swing.JRadioButton();
        lblharga = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        lblmtdbayar = new javax.swing.JLabel();
        cbpembayaran = new javax.swing.JComboBox<>();
        lblbayar = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        btBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topuplabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        topuplabel.setText("Top Up");

        lblid.setText("Masukkan ID Anda");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        lbldm.setText("Pilih Diamond");

        btngdm.add(rd15);
        rd15.setText("15 Diamond");
        rd15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd15ActionPerformed(evt);
            }
        });

        btngdm.add(rd50);
        rd50.setText("50 Diamond");
        rd50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd50ActionPerformed(evt);
            }
        });

        btngdm.add(rd125);
        rd125.setText("125 Diamond");
        rd125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd125ActionPerformed(evt);
            }
        });

        btngdm.add(rd275);
        rd275.setText("275 Diamond");
        rd275.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd275ActionPerformed(evt);
            }
        });

        btngdm.add(rd550);
        rd550.setText("550 Diamond");
        rd550.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd550ActionPerformed(evt);
            }
        });

        btngdm.add(rd725);
        rd725.setText("725 Diamond");
        rd725.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd725ActionPerformed(evt);
            }
        });

        btngdm.add(rd1000);
        rd1000.setText("1000 Diamond");
        rd1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd1000ActionPerformed(evt);
            }
        });

        lblharga.setText("Harga");

        txtharga.setEditable(false);
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        lblmtdbayar.setText("Metode Pembayaran");

        cbpembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alfamart", "Indomart", "Pulsa", "E-Wallet" }));
        cbpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpembayaranActionPerformed(evt);
            }
        });

        lblbayar.setText("Total Pembayaran");

        txtbayar.setEditable(false);
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });

        btBayar.setText("Bayar");
        btBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbldm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblid, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmtdbayar)
                                    .addComponent(lblbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rd125, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd550, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rd15))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd50)
                                    .addComponent(rd275)
                                    .addComponent(rd725)))
                            .addComponent(rd1000, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtharga)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbpembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(topuplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topuplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldm)
                    .addComponent(rd15)
                    .addComponent(rd50))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd125)
                    .addComponent(rd275))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd550)
                    .addComponent(rd725))
                .addGap(18, 18, 18)
                .addComponent(rd1000)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblharga)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmtdbayar)
                    .addComponent(cbpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbayar)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void rd50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd50ActionPerformed
        // TODO add your handling code here:
        txtharga.setText("15000");
    }//GEN-LAST:event_rd50ActionPerformed

    private void rd275ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd275ActionPerformed
        // TODO add your handling code here:
        txtharga.setText("75000");
    }//GEN-LAST:event_rd275ActionPerformed

    private void rd725ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd725ActionPerformed
        // TODO add your handling code here:
        txtharga.setText("200000");
    }//GEN-LAST:event_rd725ActionPerformed

    private void rd550ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd550ActionPerformed
        // TODO add your handling code here:
        txtharga.setText("165000");
    }//GEN-LAST:event_rd550ActionPerformed

    private void rd1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd1000ActionPerformed
        // TODO add your handling code here:
        txtharga.setText("375000");
    }//GEN-LAST:event_rd1000ActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void rd15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd15ActionPerformed
        // TODO add your handling code here:
        txtharga.setText("5000");
    }//GEN-LAST:event_rd15ActionPerformed

    private void rd125ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd125ActionPerformed
        // TODO add your handling code here:
        txtharga.setText("50000");
    }//GEN-LAST:event_rd125ActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtbayarActionPerformed

    private void cbpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpembayaranActionPerformed
        // TODO add your handling code here:
        
                if(cbpembayaran.getSelectedItem().equals("Alfamart"))
             {
                 a = Integer.parseInt(txtharga.getText());
                 b = a*10/100;
                 c = a+b;
                 
                 String hasil = Integer.toString(c);
                 txtbayar.setText(hasil);
                 
             }else if(cbpembayaran.getSelectedItem().equals("Indomart")){
                 a = Integer.parseInt(txtharga.getText());
                 b = a*11/100;
                 c = a+b;
                 
                 String hasil = Integer.toString(c);
                 txtbayar.setText(hasil);
             }else if(cbpembayaran.getSelectedItem().equals("Pulsa")){
                 a = Integer.parseInt(txtharga.getText());
                 b = a*15/100;
                 c = a+b;
                 
                 String hasil = Integer.toString(c);
                 txtbayar.setText(hasil);
             }else if(cbpembayaran.getSelectedItem().equals("E-Wallet")){
                 a = Integer.parseInt(txtharga.getText());
                 b = a*5/100;
                 c = a+b;
                 
                 String hasil = Integer.toString(c);
                 txtbayar.setText(hasil);
             }
             
        
    }//GEN-LAST:event_cbpembayaranActionPerformed

    private void btBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBayarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBayar;
    private javax.swing.ButtonGroup btngdm;
    private javax.swing.JComboBox<String> cbpembayaran;
    private javax.swing.JLabel lblbayar;
    private javax.swing.JLabel lbldm;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblmtdbayar;
    private javax.swing.JRadioButton rd1000;
    private javax.swing.JRadioButton rd125;
    private javax.swing.JRadioButton rd15;
    private javax.swing.JRadioButton rd275;
    private javax.swing.JRadioButton rd50;
    private javax.swing.JRadioButton rd550;
    private javax.swing.JRadioButton rd725;
    private javax.swing.JLabel topuplabel;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
